version: 2
jobs:
  deploy-dev:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npx serverless -- deploy -s dev

  deploy-staging:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test:staging
      - run: npx serverless -- deploy -s staging

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-dev
      # - deploy-staging:
      #   requires:
      #     - deploy-dev
