version: 2
jobs:
  init:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install

  test-dev:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - run: npm test

  deploy-dev:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:  
      - run: npx serverless -- deploy -s dev

workflows:
  version: 2
  deploy:
    jobs:
      - init
      - test-dev:
        requires:
          - init
      - deploy-dev:
        requires:
          - test-dev
