version: 2
jobs:
  deploy-dev:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      # see https://circleci.com/docs/2.0/env-vars/#using-bash_env-to-set-environment-variables
      # for reason why we have to go through $BASH_ENV
      - run:
          name: Setup AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
      - run: npm run test
      - run: npx serverless deploy

  deploy-staging:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      # see https://circleci.com/docs/2.0/env-vars/#using-bash_env-to-set-environment-variables
      # for reason why we have to go through $BASH_ENV
      - run: 
          name: Setup AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
      - run: npm run test:staging
      - run: npx serverless deploy -s staging

  deploy-prod:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      # see https://circleci.com/docs/2.0/env-vars/#using-bash_env-to-set-environment-variables
      # for reason why we have to go through $BASH_ENV
      - run: 
          name: Setup AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
      - run: npx serverless deploy -s prod

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only: master
      - deploy-staging:
          filters:
            branches:
              only:
                - release
                - /release/*
                - /rc/*
      - deploy-prod:
          filters:
            branches:
              only: production
