version: 2
jobs:
  deploy-dev:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
      - run: export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
      - run: echo $AWS_ACCESS_KEY_ID
      - run: npx serverless deploy

  deploy-staging:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - run: export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID
      - run: export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY
      - run: npm run test:staging
      - run: npx serverless deploy -s staging

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-dev
      - deploy-staging:
          requires:
            - deploy-dev
